// Shared NETRA report engine — one polished, court-familiar PDF style for every document
// (linkage/evidence report, daily digest, forecast plan). Self-contained HTML → print window.
export interface ReportSection { heading?: string; html: string }
export interface ReportOpts {
  title: string;
  subtitle: string;
  classification?: string;
  sections: ReportSection[];
  footer?: string;
}

const CSS = `
  *{box-sizing:border-box} body{font-family:Inter,system-ui,-apple-system,sans-serif;color:#0f1e33;margin:0;background:#fff}
  .page{max-width:720px;margin:0 auto;padding:44px 48px}
  .lh{display:flex;align-items:center;justify-content:space-between}
  .brand{font-weight:800;letter-spacing:.14em;font-size:15px;color:#0e2c52}
  .org{text-align:center;font-size:11px;letter-spacing:.16em;color:#5a6b82;font-weight:600}
  .org small{display:block;letter-spacing:.06em;font-weight:400;color:#8a97a8;margin-top:2px;text-transform:none}
  .classif{font-size:9px;letter-spacing:.14em;color:#b04a2f;border:1px solid #e3b7ab;border-radius:4px;padding:3px 7px;font-weight:700}
  .rule{height:3px;background:linear-gradient(90deg,#0e2c52,#2f6fb0);margin:14px 0 22px;border-radius:2px}
  h1{font-size:22px;margin:0 0 3px;color:#0e2c52} .sub{color:#5a6b82;font-size:13px;margin-bottom:22px}
  h2{font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:#0e2c52;border-bottom:1px solid #e3e8ef;padding-bottom:6px;margin:24px 0 12px}
  p{font-size:14px;line-height:1.7;margin:0 0 8px} table{width:100%;border-collapse:collapse;font-size:12px}
  th{text-align:left;color:#8a97a8;font-weight:600;border-bottom:1px solid #e3e8ef;padding:6px 8px}
  td{border-bottom:1px solid #eef2f7;padding:6px 8px;color:#26364d} .tag{display:inline-block;padding:1px 6px;border-radius:4px;font-size:11px}
  .foot{color:#9aa6b5;font-size:10px;margin-top:30px;border-top:1px solid #e3e8ef;padding-top:12px;line-height:1.6}
  @media print{.page{padding:24px 30px}}
`;

// Escape text destined for the generated report HTML. Plain-text fields (title/subtitle/heading)
// are always escaped here; callers that interpolate dynamic values (names, facts) INTO section.html
// must escape them with this too, so real FIR text can never inject markup into the print window.
export const escapeHtml = (s: unknown) =>
  String(s ?? "").replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&#39;" }[c] as string));

export function openReport(o: ReportOpts) {
  const w = window.open("", "_blank", "width=820,height=1000");
  if (!w) return;
  const body = o.sections.map((s) => `${s.heading ? `<h2>${escapeHtml(s.heading)}</h2>` : ""}${s.html}`).join("");
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(o.title)}</title><style>${CSS}</style></head><body><div class="page">
    <div class="lh">
      <div class="brand">👁️ NETRA</div>
      <div class="org">KARNATAKA STATE POLICE<small>Networked Evidence, Tracking &amp; Risk Analytics</small></div>
      <div class="classif">${escapeHtml(o.classification ?? "DECISION SUPPORT")}</div>
    </div>
    <div class="rule"></div>
    <h1>${escapeHtml(o.title)}</h1>
    <div class="sub">${escapeHtml(o.subtitle)}</div>
    ${body}
    <div class="foot">${escapeHtml(o.footer ?? "Auto-generated by NETRA · Decision support — verify against ground reports before acting (human-in-the-loop) · Prototype: synthetic data.")}</div>
  </div></body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}
